# Generated by Django 6.1 on 2026-08-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
