# Generated by Django 6.1 on 2026-09-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options_remove_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
